"use strict";

const TensorView = require('../src/TensorView.js');
const echo = console.log;

const A = TensorView([[1, 2, 3], [4, 5, 6]]).concat(TensorView([[7, 8, 9], [10, 11, 12]]), "newaxis");
const B = A.permute(2,1,0).reshape([6, 2]).permute(1,0);
echo(B.toString());
const t = TensorView([1,2,3,4,5,6], {shape:[2,3]}).slice(':','1:2');
const T = t.transpose();
const r = TensorView([[1,2,3],[4,5,6]], {shape:[3,2]});
const R = r.transpose();
const R2 = r.reshape([2,3]).slice(':','1:2');
echo(t.toNDArray());
echo(t.toArray());
echo(t.shape());
echo('---');
echo(T.toNDArray());
echo(T.toArray());
echo(T.shape());
echo('---');
echo(r.toNDArray());
echo(r.toArray());
echo(r.shape());
echo('---');
echo(R.toNDArray());
echo(R.toArray());
echo(R.shape());
echo('---');
echo(R2.toNDArray());
echo(R2.toArray());
echo(R2.shape());

echo('---');

const data = [1,2,3,4,5,6,7,8,9,10];
const data1 = [1,2,3,4,5,6];
const data2 = [7,8,9,10,11,12];
const bigdata = [1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10];

const view1 = TensorView(data, {shape:[2,5]});
const view2 = TensorView(data, {shape:[5,2]});
const view2C = TensorView([[1,2,3,4,5],[6,7,8,9,10]], {shape:[5,2]});
const view2T = view2.transpose();
const view3 = TensorView(data, {shape:[5,2]});
const view3T = view3.transpose();
const view3R = TensorView(data, {shape:[5,2]});
const view3TR = view3R.transpose();
const view4 = TensorView(data, {shape:[5,2]});
const view5 = view4.slice('2:-2:0',':');
const view12 = TensorView(data1, {shape:[2,3]}).concat(TensorView(data2, {shape:[2,3]}), 0);
const view12S = view12.slice('2:-2:0','0:2:2');
const view12T = view12S.transpose();
const viewB = TensorView(bigdata, {shape:[5,2,10]});
const viewBB = TensorView(bigdata, {shape:[5,2,5,2]});

echo('---');

echo(view1.toString());
echo(view1.toNDArray());
echo(view1.toArray());
echo('---');
echo(view2.toString());
echo(view2.toNDArray());
echo(view2.toArray());
echo('---');
echo(view2C.toString());
echo(view2C.toNDArray());
echo(view2C.toArray());
echo('---');
echo(view2T.toString());
echo(view2T.toNDArray());
echo(view2T.toArray());
echo('---');
echo(view3.toString());
echo(view3.toNDArray());
echo(view3.toArray());
echo('---');
echo(view3T.toString());
echo(view3T.toNDArray());
echo(view3T.toArray());
echo('---');
echo(view3R.toString());
echo(view3R.toNDArray());
echo(view3R.toArray());
echo('---');
echo(view3TR.toString());
echo(view3TR.toNDArray());
echo(view3TR.toArray());
echo('---');
echo(view12.toString());
echo(view12.toNDArray());
echo(view12.toArray());
echo('---');
echo(view12S.toString());
echo(view12S.toNDArray());
echo(view12S.toArray());
echo('---');
echo(view12T.toString());
echo(view12T.toNDArray());
echo(view12T.toArray());
echo('---');
echo(view4.toString());
echo(view4.toNDArray());
echo(view4.toArray());
echo('---');
echo(view5.toString());
echo(view5.toNDArray());
echo(view5.toArray());
echo('---');
echo(viewB.toString());
echo('---');
echo(viewB.toString(4));
echo('---');
echo(viewBB.toString());
echo('---');
echo(viewBB.toString(4));
